CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, username TEXT UNIQUE, pass TEXT, salt TEXT, totp TEXT, role TEXT, active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, uid INTEGER, exp INTEGER);
CREATE TABLE IF NOT EXISTS kv(k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY, kind TEXT, sort TEXT, data TEXT);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY, ts INTEGER, name TEXT, email TEXT, msg TEXT, sent INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS files(id TEXT PRIMARY KEY, type TEXT);
CREATE TABLE IF NOT EXISTS chunks(fid TEXT, n INTEGER, data BLOB, PRIMARY KEY(fid,n));
CREATE TABLE IF NOT EXISTS invites(token TEXT PRIMARY KEY, username TEXT, role TEXT, uid INTEGER, exp INTEGER);
