INSERT OR REPLACE INTO kv VALUES('settings','{"club":"Ackworth Jaguars Juniors","season":"2026/27","hero":"Train. Play. Stay. Together.","intro":"Welcome to the Ackworth Jaguars Rugby League Club. Find the latest news, fixtures, match day information and club documents here.","email":"","address":"Jaguar Park\nCarr Bridge Playing Fields\nAckworth\nWF7 7ND","map":"https://www.google.co.uk/maps/place/Ackworth+Jaguars/@53.645635,-1.3336555,17z","w3w":"Pitch|conductor.rock.sleep\nAway car park|webcams.labels.soaps\nAfter the match at Masons, Bell Lane|magic.takeover.reporting","facebook":"https://facebook.com/AckworthJaguarsJuniors","instagram":"https://instagram.com/AckworthJaguarsJuniors","youtube":"https://www.youtube.com/@AckworthJaguars","messenger":"https://m.me/AckworthJaguarsJuniors","joinUrl":"https://club.spond.com/landing/signup/ackworthjagjr/form/D8E1B79B96824EB3948814043515C4E8","joinText":"Find your age group\nCome along to a training session\nRegister and join Spond\nGet your kit","blue":"#0755a0","black":"#17191b","teal":"#14908f","compAge":"12","heroImg":"","heroOverlay":"25","mailFrom":"","turnstile":"","contactIntro":"Questions about joining, training or match days? Send us a message.","defaultRule":"These are the default match days and times. Clubs can agree to move a fixture, but if nobody can agree, the match is played on the default day and time."}');
INSERT INTO items(kind,sort,data) VALUES
('team','00','{"name":"Mini Jags","type":"Training only","slug":"mini-jags"}'),('team','06','{"age":"6","slug":"u6"}'),('team','08','{"age":"8","slug":"u8"}'),('team','10','{"age":"10","slug":"u10"}'),('team','12','{"age":"12","slug":"u12"}'),
('doc','Parents code','{"title":"Parents and supporters code of conduct","group":"Parents","url":"https://spond.com/storage/upload/27632A646D1E15438F8DCE7C7940C645/1745337144_65B34977/RFL-AJ_Parent-Supporters_Code_of_Conduct.pdf","note":"Re-upload this PDF in the portal before cancelling Spond."}'),
('doc','Players code','{"title":"Players code of conduct","group":"Players","url":"https://spond.com/storage/upload/27632A646D1E15438F8DCE7C7940C645/1744810974_B98A185A/RFL-AJ_Junior_Players_Code_of_Conduct.pdf","note":"Re-upload this PDF in the portal before cancelling Spond."}'),
('doc','Coaches code','{"title":"Coaches code of conduct","group":"Coaches","url":"https://spond.com/storage/upload/27632A646D1E15438F8DCE7C7940C645/1744819303_847777EE/RFL-AJ_Coaches_Code_of_Conduct.pdf","note":"Re-upload this PDF in the portal before cancelling Spond."}'),
('doc','Volunteers code','{"title":"Officials and volunteers code of conduct","group":"Volunteers","url":"https://spond.com/storage/upload/27632A646D1E15438F8DCE7C7940C645/1745313685_96B62242/RFL-AJ_Officials-Volunteers_Code_of_Conduct.pdf","note":"Re-upload this PDF in the portal before cancelling Spond."}'),
('doc','RFL handbook','{"title":"RFL players handbook 2025","group":"Governance","url":"https://www.rugby-league.com/uploads/docs/Parents%20Handbook%202025.pdf","note":""}'),
('doc','YJYARL','{"title":"Yorkshire Juniors (YJYARL) documentation","group":"Governance","url":"https://www.rugby-league.com/competitions/community-leagues/yorkshire-juniors-youth","note":""}'),
('doc','YJYARL constitution','{"title":"Yorkshire Juniors constitution 2025","group":"Governance","url":"https://www.rugby-league.com/uploads/docs/YJYARL%202025%20Constitution.docx","note":""}');
INSERT INTO items(kind,sort,data) VALUES
('role','001Game Day Manager','{"title":"Game Day Manager","order":"1","renew":"Registration is renewed every year with the RFL","summary":"","how":"","links":""}'),
('role','002First Aider','{"title":"First Aider","order":"2","renew":"","summary":"","how":"","links":""}'),
('role','003Coach','{"title":"Coach","order":"3","renew":"","summary":"","how":"","links":""}'),
('role','004Committee member','{"title":"Committee member","order":"4","renew":"","summary":"","how":"","links":""}');
